local app_icons = {
  ["1Password"] = ":one_password:",
  ["Affinity Designer"] = ":affinity_designer:",
  ["Affinity Photo"] = ":affinity_photo:",
  ["Affinity Affinity Store"] = ":affinity_designer:",
  ["Activity Monitor"] = ":activity_monitor:",
  ["Calendar"] = ":calendar:",
  ["Cisco AnyConnect Secure Mobility Client"] = ":cisco_anyconnect:",
  ["Code"] = ":code:",
  ["DaVinci Resolve"] = ":davinciresolve:",
  ["Default"] = ":default:",
  ["Docker"] = ":docker:",
  ["Docker Desktop"] = ":docker:",
  ["Finder"] = ":finder:",
  ["Ghostty"] = ":ghostty:",
  ["Keynote"] = ":keynote:",
  ["Logic Pro"] = ":logicpro:",
  ["Mail"] = ":mail:",
  ["Messages"] = ":messages:",
  ["Microsoft Outlook"] = ":microsoft_outlook:",
  ["Microsoft Teams"] = ":microsoft_teams:",
  ["Music"] = ":music:",
  ["Neovim"] = ":neovim:",
  ["Notes"] = ":notes:",
  ["Numbers"] = ":numbers:",
  ["Obsidian"] = ":obsidian:",
  ["Pages"] = ":pages:",
  ["Photos"] = ":photos:",
  ["Preview"] = ":pdf:",
  ["Reminders"] = ":reminders:",
  ["SF Symbols"] = ":sf_symbols:",
  ["Safari"] = ":safari:",
  ["Spotify"] = ":spotify:",
  ["System Settings"] = ":gear:",
  ["Terminal"] = ":terminal:",
  ["TextEdit"] = ":textedit:",
  ["UTM"] = ":utm:",
  ["VLC"] = ":vlc:",
  ["Vicinae"] = ":spotlight:",
  ["Vim"] = ":vim:",
  ["WhatsApp"] = ":whats_app:",
  ["Xcode"] = ":xcode:",
  ["Zen"] = ":zen_browser:",
  ["zen"] = ":zen_browser:",
  ["Zed"] = ":zed:",
  ["Zen Browser"] = ":zen_browser:",
  ["neovim"] = ":neovim:",
  ["nvim"] = ":neovim:",
  ["‎WhatsApp"] = ":whats_app:",
}

return function(app_name)
  return app_icons[app_name] or ":default:"
end
