onboarding = false

[theme]
name = "catppuccin"

[theme.custom]
panel_bg = "#24273a"
accent = "#c6a0f6"
surface0 = "#363a4f"
surface1 = "#494d64"
surface_dim = "#1e2030"
overlay0 = "#6e738d"
overlay1 = "#8087a2"
text = "#cad3f5"
subtext0 = "#a5adcb"
mauve = "#c6a0f6"
green = "#a6da95"
yellow = "#eed49f"
red = "#ed8796"
blue = "#8aadf4"
teal = "#8bd5ca"
peach = "#f5a97f"

[keys]
prefix = "ctrl+space"
reload_config = "prefix+r"
resize_mode = ""
split_vertical = "prefix+|"
split_horizontal = "prefix+minus"
new_tab = "prefix+c"
focus_pane_left = "ctrl+h"
focus_pane_down = "ctrl+j"
focus_pane_up = "ctrl+k"
focus_pane_right = "ctrl+l"
zoom = "prefix+m"
close_pane = "prefix+x"
close_tab = "prefix+shift+x"

[[keys.command]]
key = "prefix+h"
type = "shell"
command = '"$HERDR_BIN_PATH" pane resize --direction left --current'
description = "resize pane left"

[[keys.command]]
key = "prefix+j"
type = "shell"
command = '"$HERDR_BIN_PATH" pane resize --direction down --current'
description = "resize pane down"

[[keys.command]]
key = "prefix+k"
type = "shell"
command = '"$HERDR_BIN_PATH" pane resize --direction up --current'
description = "resize pane up"

[[keys.command]]
key = "prefix+l"
type = "shell"
command = '"$HERDR_BIN_PATH" pane resize --direction right --current'
description = "resize pane right"

[ui]
show_agent_labels_on_pane_borders = true
prompt_new_tab_name = false
