# Check if this can be removed
ZSH_DISABLE_COMPFIX=true

# load zgen
source "${HOME}/.zgen/zgen.zsh"

# if the init scipt doesn't exist
if ! zgen saved; then


  # specify plugins here
  zgen oh-my-zsh

  zgen oh-my-zsh plugins/git
  zgen oh-my-zsh plugins/sudo
  zgen oh-my-zsh plugins/command-not-found
  zgen load zsh-users/zsh-syntax-highlighting
  zgen load zsh-users/zsh-completions

  zgen load denysdovhan/spaceship-prompt spaceship

  SPACESHIP_TIME_SHOW=true
  
  # generate the init script from plugins above
  zgen save
fi

alias magit=emacs
alias gg=lazygit
